### ISSUE TITLE
Option to hide the duplicate title present in description 

### ISSUE THREAD

**Issue by P0bo** [prof18/feed-flow#186]
Some websites provide article titles twice, once in the title and once in the description with some extra info, which, while browsing, is quite annoying to see the same title. Some RSS clients, for example, Feedly, remove the duplicate title from the description. Below is the visual representation of how Feedly handles it and how FeedFlow handles it.

>The white text is the title, and the greyed text is the description.
![Screenshot_2024-04-10-02-42-22-74_14f923dba7aa743f2820ba9cc8abb3d9](https://github.com/Ashinch/ReadYou/assets/154865357/43f67f19-dee3-4c1f-b85e-6579ffdce7cf)

>FeedFlow
![Screenshot_2024-04-10-02-47-23-47_ec2eb6fa460e4a1f71f8b51a239fd3fc](https://github.com/prof18/feed-flow/assets/154865357/0c0fc72b-fdcb-4717-8734-ac48cb55c762)

Another problem that happens because of that is I get so many feed updates a day (and so many titles are the same). I have to distinguish most of them from the description, which becomes quite tiring and distracting when there are the same names in the description and title.

I have 4 work feeds which do the same (I can't share the feed link), but this above example is from this site https://nyaa.land/?page=rss.

If the app introduces the option to hide the duplicate titles, that would be really helpful. My work involves a lot of moving, so I only have access to my tablet (and phone) while working, and I don't really have the option of having a browser tab of Feedly open all the time. One of the only truly minimal apps that support tablet UI is FeedFlow. I tried other apps too, but none have the option to hide duplicate titles, including FeedFlow, but this had the best UI.

I greatly thank you for making this great app. This has been my main RSS reader for the last 4 months, and has saved me a lot of time.

Please look at the issue. This will really help me do my work more efficiently and possibly save so much time for those who also have subscribed to similar feeds.

Thanks in advance.

**Comment by prof18** [comment]
Thanks for the nice words! 
I didn't know about such cases, thanks for reporting it! I will definitely look into it for the future releases

**Comment by onnesoom** [comment]
Hello , first of all thank u for this great app , this is exactly what i needed .

however the same issue  (duplicate title present in description) has made my feed articles heavily  cluttered  , I have seen that @P0bo has made this issue in more rss readers  , some of them has implemented it after that (ex - anivu) and some has assigned dev to implement thsi (ex - read you) . but i like to use feed flow than those readers coz they open articles in a reader as opposed to browser like feed flow and also i like how minimal feed flow is . 

If i may can we have some sort of eta please if possible because this will impact my articles browsing greatly .

**Comment by P0bo** [comment]
I feel you brother 
![Screenshot_2024-08-01-12-54-52-04_ec2eb6fa460e4a1f71f8b51a239fd3fc.jpg](https://github.com/user-attachments/assets/f945173e-09f1-4d35-b9ab-b4f0a9a0af02)

**Comment by Buxuna** [comment]
> however the same issue  (duplicate title present in description) has made my feed articles heavily  cluttered  , I have seen that @P0bo has made this issue in more rss readers  , some of them has implemented it after that (ex - anivu) and some has assigned dev to implement thsi (ex - read you) . but i like to use feed flow than those readers coz they open articles in a reader as opposed to browser like feed flow and also i like how minimal feed flow is . 


i have tried all those apps because of these single feature i have been making rounds of them . i always want to settle to feed-flow  but this single feature is what prevents me from doing . currently im not even sure what to use . read you is not for me , anivu design is heavily customisable but the app is really unstable , feeder is not so minimal . i have found nothing that comes close to the minimalism of feed flow  thats why i have been waiting for this feature to come . so can can ditch the web app of Feedly .

**Comment by prof18** [comment]
The feature will be available on the next release in some weeks
