### ISSUE TITLE
Build for Intel Mac

### ISSUE THREAD

**Issue by bexelbie** [prof18/feed-flow#320]
Is there a possibility of an Intel build?  I haven't replaced my personal laptop yet.

**Comment by prof18** [comment]
Unfortunately not. It's not trivial (or even possible for now, afaik) to provide a universal binary: https://youtrack.jetbrains.com/issue/CMP-5125

**Comment by sorenpeter** [comment]
Any change it have become easier to make universal build or special builds for intel mac computer here in 2026?
I'm also on a older MacBook and I just discovered that FeedFlow got sync support via Dropbox, witch alleviate the need for a (self)hosted RSS-service.

**Comment by prof18** [comment]
Hey! Unfortunately, it hasn't gotten easier, actually, the opposite is happening. Both Kotlin and Compose Multiplatform are phasing out Intel Mac support:

- Kotlin 2.3.0 has demoted macosX64 and other x64 Apple targets to [Tier 3 support](https://kotlinlang.org/docs/whatsnew23.html#demotion-of-x86-64-apple-targets-to-tier-3), meaning they're no longer guaranteed to be tested on CI, and binary compatibility between compiler releases might not be provided. The plan is to completely remove support for x86_64 Apple targets in Kotlin 2.4.0.

- Compose Multiplatform follows the same trajectory ([CMP-9543](https://youtrack.jetbrains.com/issue/CMP-9543/Drop-apple-x64-targets-in-CMP)).

This means supporting Intel Macs would create a significant maintenance burden. I'd need to stay on older Kotlin versions or deal with increasingly unstable/unsupported tooling. Since Apple themselves transitioned to Apple Silicon years ago and Intel Macs are being phased out across the ecosystem, I've decided not to provide Intel Mac builds :(

**Comment by bexelbie** [comment]
I respect the choice. It's the right one for the project. Thank you
